name: Terraform Validation

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  validate:
    name: Terraform Validation and Security
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        shell: bash
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Terraform dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-
            
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false
          
      - name: Terraform Format
        run: terraform fmt -check -recursive
        continue-on-error: true
        
      - name: Terraform Init
        run: |
          terraform init \
            -backend=false \
            -reconfigure \
            -upgrade
        env:
          TF_VAR_environment: ${{ github.event_name == 'pull_request' && 'pr' || 'main' }}
          
      - name: Terraform Validate
        run: |
          terraform validate \
            -json \
            -no-color
        continue-on-error: true
        
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        continue-on-error: true
        env:
          TF_VAR_environment: ${{ github.event_name == 'pull_request' && 'pr' || 'main' }} 