name: Unit Tests

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-unit
      cancel-in-progress: true
    defaults:
      run:
        shell: bash
    env:
      GO111MODULE: on
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
          check-latest: true
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod
            
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
          terraform_wrapper: false
          
      - name: Download go modules
        working-directory: tests
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org,direct
          
      - name: Run unit tests
        working-directory: tests
        run: |
          go run gotest.tools/gotestsum@latest \
            --format short-verbose \
            --junitfile test-results.xml \
            -- -tags=unit \
            -race \
            -coverprofile=coverage.out \
            -covermode=atomic
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
          TF_IN_AUTOMATION: true
          TF_INPUT: false
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: |
            tests/test-results.xml
            tests/coverage.out
          retention-days: 7 